name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        cd app
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd app
        python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t local-django-app:${{ github.sha }} .

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Deploy Locally (Simulated)
      run: |
        docker stop local-django-container || true
        docker rm local-django-container || true
        docker run -d --name local-django-container -p 8000:8000 local-django-app:${{ github.sha }}
